//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public Nullable<int> PhongBan_id { get; set; }
        public string Name { get; set; }
        public string Birthdate { get; set; }
        public string Address { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
