//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        public KHOA()
        {
            this.SVIENs = new HashSet<SVIEN>();
        }
    
        public string MAKHOA { get; set; }
        public string TENKHOA { get; set; }
        public int NAMTHANHLAP { get; set; }
    
        public virtual ICollection<SVIEN> SVIENs { get; set; }
    }
}
